<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="GM.RateLimiting" Version="1.0.0" />
        <PackageReference Include="GM.RateLimiting.Http" Version="1.0.0" />
        <PackageReference Include="GM.RateLimiting.Redis" Version="1.0.0" />
        <PackageReference Include="GM.Caching" Version="1.0.0" />
        <PackageReference Include="GM.Caching.Redis" Version="1.0.0" />
        <PackageReference Include="GM.DistributedLock" Version="1.0.0" />
    </ItemGroup>

</Project>
